version: '3.5'

services:
  backend:
    build: .
    image: backend:latest
    networks:
      - backend
    command: yarn start:dev
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/backend
      - /usr/src/backend/node_modules
    ports:
      - 3000:3000

networks:
  backend:
    driver: overlay
    driver_opts:
      encrypted: 'true'
